### PR TITLE
attempting to modernize dev_server

### PR DESCRIPTION
**Pull request by bunnybones1**
Hey there,
I have a need for something much like what you've written here.
I made a few edits to make it run against the latest `deno/std` and `abc`
It seems to work fine but I'm not entirely sure to be honest (I usually just do front-end dev and graphics)

Futhermore, I'm trying to get sourcemaps to work but it looks like CompilerOptions don't do anything with `sourceMaps` or `inlineSourceMap`
In fact most of the CompilerOptions I tried made no difference to the output.
I wonder if I was doing something wrong.

### CODE REVIEW

**Comment by zhmushan** [comment]
Thank you very much for spending time on this. Deno has changed a lot during this time, I will try your patch right away.

**Comment by zhmushan** [comment]
> Futhermore, I'm trying to get sourcemaps to work but it looks like CompilerOptions don't do anything with `sourceMaps` or `inlineSourceMap`
> In fact most of the CompilerOptions I tried made no difference to the output.
> I wonder if I was doing something wrong.

Sorry not supported (https://github.com/denoland/deno/issues/4499)

**Comment by bunnybones1** [comment]
Thanks for confirming that. I hope that gets addressed in the near future.
Until then, I suppose productive development without source-maps is possible, but it's a different mindset :)

**Review by zhmushan — APPROVED** [review]
Anyway, thanks for your pr

**Pull request merged**
